spring:
  datasource:
    url: jdbc:h2:mem:backend_test_application_db
    username: php
    password:
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

